apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petshop-api-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # IMPORTANT: Replace with your actual GitHub repo URL
    repoURL: 'https://github.com/CarlosRodriguez260/LocalMonorepoCluster.git'
    path: apps/petshop-api/k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: petshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true